services:
  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  bandage:
    build: .
    restart: always
    ports:
      - "8443:3000"
    volumes:
      - ${HOME}/NIGMS-Sandbox-Pangenomics-Module:${HOME}/NIGMS-Sandbox-Pangenomics-Module:rw
